@startuml
skinparam ConditionEndStyle hline

title Блок-схема потока данных поставки результатов анализов

start

partition "Legacy Контур: LIS" {
    :Лаборант вносит/верифицирует результаты исследований;
    :Формирование JSON-пакета\n(включает client_id, уникальный номер исследования и данные);
    :Отправка события в RabbitMQ по протоколу AMQP;
}

partition "Шина данных: RabbitMQ" {
    :Сохранение сообщения на диск ;
    :Отправка сигнала Publisher Confirm назад в LIS;
}

partition "Внутренний ИТ-контур: CRM Service" {
    :Воркер CRM считывает сообщение из очереди;

    note right
        Контур бизнес-дедупликации
        (Защита от дублирования записей)
    end note

    if (В PostgreSQL уже есть запись с таким номером исследования?) then (да)
        :Логирование дубликата (Пропуск записи);
    else (нет)
        :Сохранение результатов анализов в электронную мед. карту;
    endif

    :Отправка сигнала Consumer Ack в RabbitMQ (Удаление из очереди);
    :Публикация в брокер события "АнализыДобавлены";
}

partition "Внутренний ИТ-контур: Notification Service" {
    :Вычитка события "АнализыДобавлены";
    :Отправка Push-уведомления "Ваши анализы готовы!";
}

partition "Клиент: Мобильное приложение" {
    :Пациент получает Push и открывает экран анализов;
    :Моментальное чтение обновленных данных;
}

stop
@enduml
